import type {Metadata} from "next";
import {founders,story} from "@/lib/site";
export const metadata:Metadata={title:"Nuestra historia",description:"La historia y las personas detrás de CAOS Records, fundada en Panamá en 2026 por Xavi y Agm."};
export default function AboutPage(){return <>
<section className="about-cover"><div><p className="eyebrow">PANAMÁ / 2026</p><h1>Nuestra<br/>historia.</h1></div><img src="/logo-white.png" width="440" height="440" alt="CAOS Records"/></section>
<section className="history-section"><div className="history-heading"><p className="eyebrow">EL COMIENZO</p><h2>Construir<br/>con los artistas.</h2></div><div className="history-copy">{story.map(p=><p key={p}>{p}</p>)}</div></section>
<section className="history-section history-dark"><div className="history-heading"><p className="eyebrow">EL NOMBRE</p><h2>Antes de tomar forma,<br/>hay movimiento.</h2></div><div className="history-copy"><p>Las ideas se cruzan. Los artistas experimentan. Las personas se encuentran. Las oportunidades aparecen antes de tener una etiqueta.</p><p>CAOS es nuestro nombre para ese espacio. No porque el objetivo sea el desorden, sino porque muchas veces ahí comienza una dirección interesante.</p></div></section>
<section className="history-section"><div className="history-heading"><p className="eyebrow">NUESTRA FORMA DE TRABAJAR</p><h2>Identidad<br/>y dirección.</h2></div><div className="history-copy"><p>Una carrera debe potenciar lo que hace distinto a un artista. Queremos que cada proyecto conserve su carácter al crecer, sin reducirlo a una fórmula fácil de vender.</p><p>Preferimos construir menos cosas y hacerlas bien, en lugar de acumular nombres que nunca se conviertan en relaciones de trabajo reales. Un lanzamiento, un concierto o una colaboración tienen más sentido cuando forman parte de una dirección más amplia.</p><p>Panamá es nuestro punto de partida. La intención es crear relaciones que puedan moverse por Centroamérica, el Caribe, Latinoamérica y más allá, conforme el trabajo se gane ese alcance.</p></div></section>
<section className="founder-section"><p className="eyebrow">LOS FUNDADORES</p><div>{founders.map(f=><article key={f.alias}><h2>{f.alias}</h2><p>{f.name}</p><a href={f.instagram} target="_blank" rel="noreferrer">{f.handle} </a></article>)}</div></section></>}
