import {pageMetadata,siteDescription} from "@/lib/seo";
export const metadata=pageMetadata("CAOS Records",siteDescription,"/");
import Link from "next/link";
import Logo3D from "@/components/Logo3D";
import RecordSleeve from "@/components/RecordSleeve";
import RecordStack from "@/components/RecordStack";
import {instagram,officialEmail} from "@/lib/site";
export default function HomePage(){return <div className="sculptural-home">
 <section className="label-cover"><div className="cover-meta"><span>Contratación / Representación / Sello</span></div><h1 className="sr-only">CAOS Records — contratación, representación y sello discográfico</h1><Logo3D/><div className="label-cover-bottom"><p>Artistas, escenarios<br/>y proyectos musicales.</p><Link href="/artists" className="text-link">CONOCE A NUESTROS ARTISTAS</Link></div></section>
 <section className="music-workbench"><div className="workbench-copy" data-reveal><p className="eyebrow">MÚSICA, EN TODAS SUS FORMAS</p><h2>Del primer tema<br/>al siguiente<br/><em>escenario.</em></h2><p>Un proyecto puede empezar con una canción, una actuación o una colaboración. Trabajamos en contratación, representación y lanzamientos, con una relación definida para cada artista.</p><p>El equipo del artista, los promotores y los colaboradores tienen necesidades distintas. Nuestro trabajo es entender el proyecto y organizar la conversación que corresponde.</p><Link href="/contact" className="text-link">HABLEMOS DE TU PROYECTO</Link></div><RecordStack/></section>
 <section id="booking" className="live-cutout"><div className="live-title" data-reveal><p className="eyebrow">CONTRATACIÓN ARTÍSTICA</p><h2>EN<br/><span>VIVO.</span></h2><Link className="text-link" href="/booking">PROPONER UN EVENTO</Link></div><div className="live-copy" data-reveal><h3>Una sala.<br/>Un festival.<br/>Tu próximo evento.</h3><p>Recibimos propuestas de conciertos, eventos privados y colaboraciones con marcas. Para revisar una actuación necesitamos conocer el artista, la fecha, la ciudad, el recinto y el presupuesto previsto.</p><p>También importa cómo será el evento: aforo, público, formato de la presentación y necesidades técnicas. Si todavía estás definiendo la producción, puedes contarnos lo que ya tienes.</p><div className="live-footnote"><p>Las solicitudes se revisan con el equipo. La disponibilidad y las condiciones se confirman para cada propuesta.</p><Link href="/booking" className="text-link">CONSULTAR DISPONIBILIDAD</Link></div></div></section>
 <section className="home-label label-floating"><RecordSleeve/><div className="label-details" data-reveal><p className="eyebrow">DISCOGRÁFICA</p><h2>El sello.</h2><p>Sencillos, álbumes y colaboraciones. El trabajo de un lanzamiento abarca la música, el arte y la forma de presentarlo al público.</p><p>Una relación de representación no obliga a publicar con el sello. Cada proyecto se plantea según lo que el artista necesita y el acuerdo que se construya con su equipo.</p><div className="catalog-status"><h3>Próximos lanzamientos</h3><p>El catálogo de CAOS está en desarrollo. Publicaremos los títulos, las portadas, los créditos y los enlaces de escucha cuando estén anunciados.</p></div><Link href="/records" className="text-link">EXPLORAR EL SELLO</Link></div></section>
 <section className="representation-notes"><div data-reveal><p className="eyebrow">REPRESENTACIÓN</p><h2>El trabajo<br/>detrás del artista.</h2></div><div data-reveal><p className="lead-copy">Las decisiones de una carrera van más allá del próximo lanzamiento.</p><p>La representación se trabaja con el artista y su equipo: qué proyectos desarrollar, qué oportunidades estudiar y cómo darles continuidad. El alcance de esa relación se conversa de forma individual.</p><p>Si buscas una colaboración, envíanos la idea, los participantes y los plazos. Si quieres presentar tu música, incluye enlaces de escucha y una breve descripción del proyecto.</p><Link href="/contact" className="text-link">CONTACTAR AL EQUIPO</Link></div></section>
 <section className="contact-arc" data-reveal><div><p className="eyebrow">PARA LO QUE VIENE</p><h2>Hablemos.</h2></div><div><p>Actuaciones, música, colaboraciones.<br/>Cuéntanos qué estás preparando.</p><a className="contact-mail" href={`mailto:${officialEmail}`}>{officialEmail}</a><a className="text-link" href={instagram.url} target="_blank" rel="noreferrer">@caos.records</a></div></section>
 </div>}
