import {pageMetadata} from "@/lib/seo";
import type {Metadata} from "next";
import Link from "next/link";
import InnerHero from "@/components/InnerHero";
import InkStamp from "@/components/InkStamp";
export const metadata:Metadata=pageMetadata('El sello','La visión del sello independiente de CAOS Records. Canciones, identidad y proyectos que queremos construir junto a los artistas.',"/records");
export default function RecordsPage(){return <div className="label-page">
<InnerHero label="DISCOGRÁFICA" title="EL SELLO" accent="" copy="Queremos publicar música que tenga algo propio que decir. Construir un catálogo con identidad, junto a artistas que crean en lo que están haciendo."/>
<section className="label-manifesto"><div className="stamp-paper"><p className="eyebrow">MÚSICA CON IDENTIDAD</p><InkStamp/><p className="stamp-caption">Una marca compartida.<br/>Muchas formas de sonar.</p></div><div className="label-letter"><p className="eyebrow">LO QUE QUEREMOS CONSTRUIR</p><h2>Que cada canción<br/>deje su marca.</h2><p>Nos interesa la música que permite reconocer a quien está detrás: su forma de escribir, su voz, sus influencias y su manera de contar las cosas. Queremos que el sello sea un espacio para desarrollar esa identidad y darle una presentación a su altura.</p><p>La intención es trabajar junto al artista en lo que rodea a un lanzamiento: cómo se cuenta su historia, qué imagen lo acompaña y cómo se conecta con las personas que pueden hacerlo suyo. La canción es el punto de partida; la dirección se construye conversando.</p><p>Estamos dando forma a nuestro primer catálogo. Queremos que cada sencillo, proyecto y colaboración tenga un lugar dentro de él, con tiempo para cuidar las decisiones y con claridad sobre lo que aporta cada persona.</p></div></section>
<section className="label-intentions"><div><p className="eyebrow">UNA VISIÓN COMPARTIDA</p><h2>El sonido es tuyo.<br/>La construcción,<br/>en conjunto.</h2></div><div><article><h3>Identidad antes que fórmula.</h3><p>Queremos acompañar propuestas que puedan evolucionar sin perder su carácter. Explorar un sonido nuevo, cruzar géneros o cambiar de dirección también puede ser parte de encontrar una voz propia.</p></article><article><h3>Una publicación con sentido.</h3><p>Nos proponemos cuidar la relación entre la música, la portada, los créditos y las piezas que la presentan. Cada proyecto necesita su propio ritmo y una idea clara de lo que quiere comunicar.</p></article><article><h3>Relaciones que puedan crecer.</h3><p>Buscamos conversaciones honestas sobre las expectativas, los tiempos y el alcance del trabajo. Las condiciones de cada lanzamiento se acuerdan con el artista; la representación y la publicación con el sello se conversan por separado.</p></article></div></section>
<section className="label-invitation"><p className="eyebrow">EL CATÁLOGO ESTÁ EN DESARROLLO</p><h2>Lo próximo empieza<br/>con una escucha.</h2><p>Los lanzamientos se anunciarán aquí con sus portadas, créditos y enlaces oficiales. Si quieres presentarnos tu música, envía enlaces de escucha, una breve descripción del proyecto y qué te gustaría construir con nosotros.</p><Link href="/contact" className="text-link">PRESENTAR UN PROYECTO</Link></section>
</div>}
