"use client";
import {useState} from "react";
import Link from "next/link";
import type {Artist} from "@/data/artists";
export default function ArtistMusic({artist,compact=false}:{artist:Artist;compact?:boolean}){
 const tracks=compact?artist.releases?.slice(0,3):artist.releases;
 const [active,setActive]=useState(0);const [playing,setPlaying]=useState(false);if(!tracks?.length)return null;const selected=tracks[active];
 return <section className="artist-music"><div className="music-intro"><p className="eyebrow">LA MÚSICA DE {artist.name.toUpperCase()}</p><h2>Escucha<br/>a {artist.name}.</h2><p>Canciones y colaboraciones publicadas en su canal oficial.</p><a className="text-link" href={artist.links?.youtube} target="_blank" rel="noreferrer">CANAL OFICIAL</a></div><div className="music-selection"><div className="music-feature"><button type="button" className="music-art" onClick={()=>setPlaying(true)} aria-label={`Reproducir ${selected.title} aquí`}>{selected.artwork?<img src={selected.artwork} alt={`Imagen de ${selected.title} publicada por ${artist.name}`} loading="lazy"/>:<span className="music-art-fallback">{artist.monogram || artist.name}</span>}<span className="music-art-label">REPRODUCIR</span></button><div><p className="eyebrow">{selected.credit}</p><h3>{selected.title}</h3><p>{selected.duration}</p></div></div>{playing&&<div className="embedded-player"><iframe key={selected.videoId} title={`${selected.title} — ${artist.name}`} src={`https://www.youtube-nocookie.com/embed/${selected.videoId}?autoplay=1&playsinline=1&rel=0`} allow="autoplay; encrypted-media; picture-in-picture; fullscreen" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><div><button type="button" className="text-link" onClick={()=>setPlaying(false)}>CERRAR REPRODUCTOR</button><a className="text-link" href={`https://www.youtube.com/watch?v=${selected.videoId}`} target="_blank" rel="noreferrer">ABRIR EN YOUTUBE</a></div></div>}<div className="track-list">{tracks.map((track,i)=><button key={track.videoId} type="button" className={i===active?'active':''} onClick={()=>setActive(i)} aria-pressed={i===active}><span>{track.title}<small>{track.credit}</small></span><span>{track.duration}</span></button>)}</div>{compact&&<Link className="text-link all-music" href={`/artists/${artist.slug}`}>MÁS DE {artist.name.toUpperCase()}</Link>}</div></section>
}
