"use client";
import {createContext,useContext,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {PRIVACY_VERSION,readPreference,STORAGE_KEY} from '@/lib/privacy';
const PrivacyContext=createContext({mediaAllowed:false,allowMedia:()=>{},openPreferences:()=>{}});
export const usePrivacy=()=>useContext(PrivacyContext);
export function PrivacySettingsButton(){const {openPreferences}=usePrivacy();return <button type="button" onClick={openPreferences}>Configurar cookies</button>}
export default function PrivacyProvider({children}:{children:React.ReactNode}){
 const [choice,setChoice]=useState<boolean|null>(null);const [ready,setReady]=useState(false);const [draft,setDraft]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const memory=useRef<string|null>(null);
 useEffect(()=>{const sync=()=>{let raw=memory.current;try{raw=localStorage.getItem(STORAGE_KEY)||raw;}catch{}setChoice(readPreference(raw));setReady(true);};const storage=(event:StorageEvent)=>{if(event.key===STORAGE_KEY||event.key===null){memory.current=event.newValue;sync();}};sync();const timer=setInterval(sync,60000);window.addEventListener('storage',storage);window.addEventListener('focus',sync);return ()=>{clearInterval(timer);window.removeEventListener('storage',storage);window.removeEventListener('focus',sync);};},[]);
 function save(media:boolean){const raw=JSON.stringify({version:PRIVACY_VERSION,media,savedAt:Date.now()});memory.current=raw;setChoice(media);try{localStorage.setItem(STORAGE_KEY,raw);}catch{}dialog.current?.close();}
 function openPreferences(){setDraft(choice===true);dialog.current?.showModal();}
 return <PrivacyContext.Provider value={{mediaAllowed:choice===true,allowMedia:()=>save(true),openPreferences}}>{children}{ready&&choice===null&&<aside className="privacy-banner" aria-label="Preferencias de privacidad"><div><strong>Tú decides qué se carga.</strong><p>La web funciona sin cookies opcionales. YouTube y sus imágenes solo se cargan si permites multimedia. Guardamos tu elección en este navegador durante 180 días. <Link href="/cookies">Más información</Link></p></div><div className="privacy-actions"><button onClick={()=>save(false)}>Solo necesarias</button><button onClick={()=>save(true)}>Permitir multimedia</button><button onClick={openPreferences}>Configurar</button></div></aside>}<dialog ref={dialog} className="privacy-dialog" aria-labelledby="privacy-title"><h2 id="privacy-title">Tu privacidad.</h2><p>El almacenamiento de preferencias recuerda tu decisión. No usamos herramientas de analítica ni píxeles publicitarios.</p><label><input type="checkbox" checked={draft} onChange={e=>setDraft(e.target.checked)}/> Permitir contenido multimedia de YouTube</label><p>Al activarlo, Google recibe datos de conexión y puede usar almacenamiento propio. Al desactivarlo retiramos los reproductores y las imágenes externas; esto no borra datos ya recibidos por Google.</p><Link href="/privacy">Leer la política de privacidad</Link><div className="privacy-actions"><button onClick={()=>save(draft)}>Guardar preferencias</button><button onClick={()=>dialog.current?.close()}>Cerrar</button></div></dialog></PrivacyContext.Provider>
}
