"use client";
import {useState} from 'react';
import Link from 'next/link';
const channels=[
 {name:'Escenario',title:'La próxima fecha empieza aquí.',text:'Una propuesta de actuación necesita contexto. Cuéntanos dónde será, a quién va dirigida y qué tienes previsto para la producción.',items:['Salas y festivales','Eventos privados','Propuestas de marcas'],href:'/booking',action:'Proponer una actuación'},
 {name:'Carrera',title:'Dar continuidad a lo que creas.',text:'Conversamos con cada artista sobre su proyecto, sus prioridades y las oportunidades que quiere explorar. El alcance de la representación se acuerda con su equipo.',items:['Representación artística','Colaboraciones','Coordinación de proyectos'],href:'/contact',action:'Hablar de representación'},
 {name:'Música',title:'De la sesión al lanzamiento.',text:'Canciones y producciones para la pista necesitan música, créditos e identidad visual. Presenta tu proyecto con enlaces de escucha y cuéntanos qué estás preparando.',items:['Sencillos y álbumes','Identidad del lanzamiento','Propuestas al sello'],href:'/records',action:'Conocer el sello'}
];
export default function ServiceMixer(){const [active,setActive]=useState(0);const channel=channels[active];return <section className="service-mixer" aria-labelledby="mixer-title"><div className="mixer-heading"><p className="eyebrow">CADA PROYECTO TIENE SU FRECUENCIA</p><h2 id="mixer-title">Conecta<br/><em>tu idea.</em></h2><p>Elige qué quieres mover.</p></div><div className="mix-console"><div className="console-top"><img src="/logo-white.png" alt="CAOS Records" width="90" height="90"/><span>LA MESA DE TRABAJO</span></div><div className="console-channels" role="group" aria-label="Área del proyecto">{channels.map((item,i)=><button key={item.name} className={i===active?'selected':''} onClick={()=>setActive(i)} aria-pressed={i===active}><span className="fader-track" aria-hidden="true"><span className="fader-knob"/></span><span>{item.name}</span></button>)}</div><svg className="console-cable" viewBox="0 0 500 130" fill="none" aria-hidden="true"><path d="M100 0 C100 105 450 10 415 86 C390 144 68 60 5 125" stroke="#080808" strokeWidth="13"/><path d="M100 0 C100 105 450 10 415 86 C390 144 68 60 5 125" stroke="#777" strokeWidth="2"/></svg></div><div className="mixer-detail" aria-live="polite" aria-atomic="true" key={active}><p className="eyebrow">{channel.name}</p><h3>{channel.title}</h3><p>{channel.text}</p><ul>{channel.items.map(item=><li key={item}>{item}</li>)}</ul><Link className="text-link" href={channel.href}>{channel.action.toUpperCase()}</Link></div></section>}
