import 'server-only';
import {createSign,randomUUID} from 'node:crypto';
import {Release,validateRelease} from './releases';
export const headers=['id','slug','title','artist_slug','description','cover_url','links_json','published','created_at','updated_at'];
export function sheetsConfigured(){return Boolean(process.env.GOOGLE_SHEETS_ID&&process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL&&process.env.GOOGLE_PRIVATE_KEY);}
let token:{value:string;expires:number}|undefined;
async function accessToken(){if(token&&token.expires>Date.now())return token.value;const now=Math.floor(Date.now()/1000);const encode=(v:unknown)=>Buffer.from(JSON.stringify(v)).toString('base64url');const payload=encode({alg:'RS256',typ:'JWT'})+'.'+encode({iss:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,scope:'https://www.googleapis.com/auth/spreadsheets',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3600});const signer=createSign('RSA-SHA256');signer.update(payload);const signature=signer.sign(process.env.GOOGLE_PRIVATE_KEY!.replace(/\\n/g,'\n'),'base64url');const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:payload+'.'+signature}),cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('No se pudo autenticar la conexión con Google.');const data=await response.json();if(!data.access_token)throw Error('Google no devolvió autorización.');token={value:data.access_token,expires:Date.now()+3000000};return token.value;}
async function request(range:string,method='GET',body?:unknown,append=false){if(!sheetsConfigured())throw Error('Falta conectar Google Sheets.');const url=`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(process.env.GOOGLE_SHEETS_ID!)}/values/${encodeURIComponent(range)}${append?':append':''}${method==='GET'?'':'?valueInputOption=RAW'+(append?'&insertDataOption=INSERT_ROWS':'')}`;const response=await fetch(url,{method,headers:{Authorization:`Bearer ${await accessToken()}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw Error('No se pudo leer o guardar en Google Sheets. Revisa permisos y configuración.');return response.json();}
export async function readRows(){const data=await request("'Lanzamientos'!A:J");const rows:string[][]=data.values||[];if(!rows.length||headers.some((v,i)=>rows[0][i]!==v))throw Error('La pestaña Lanzamientos no tiene las columnas de la plantilla.');return rows;}
export function parseRow(row:string[]):Release|null{try{const r:Release={id:row[0],slug:row[1],title:row[2],artist_slug:row[3],description:row[4]||'',cover_url:row[5],links:JSON.parse(row[6]||'[]'),published:row[7]==='TRUE',created_at:row[8],updated_at:row[9]};validateRelease(r);return r;}catch{return null;}}
export async function listReleases(){const rows=await readRows();return rows.slice(1).map(parseRow).filter((r):r is Release=>r!==null);}
export async function saveRelease(input:Release){validateRelease(input);const rows=await readRows();const index=rows.findIndex((r,i)=>i>0&&r[0]===input.id);if(rows.some((r,i)=>i>0&&i!==index&&r[1]===input.slug))throw Error('Ya existe un lanzamiento con esa dirección.');if(index>0&&rows[index][1]!==input.slug)throw Error('La dirección de un lanzamiento guardado no se puede cambiar.');if(index>0&&rows[index][9]!==input.updated_at)throw Error('Este lanzamiento cambió. Recarga el panel antes de editarlo.');const now=new Date().toISOString();const r={...input,id:index>0?rows[index][0]:randomUUID(),created_at:index>0?rows[index][8]:now,updated_at:now};const values=[[r.id,r.slug,r.title.trim(),r.artist_slug,r.description.trim(),r.cover_url,JSON.stringify(r.links),r.published?'TRUE':'FALSE',r.created_at,r.updated_at]];await request(index>0?`'Lanzamientos'!A${index+1}:J${index+1}`:"'Lanzamientos'!A:J",index>0?'PUT':'POST',{values},index<0);return r;}
