import {NextResponse} from 'next/server';
import {adminConfigured,cookieName,isAdmin,matchesPassword,sameOrigin,sessionToken} from '@/lib/admin-auth';
import {sheetsConfigured} from '@/lib/sheets';
export const runtime='nodejs';export const dynamic='force-dynamic';
// Límite por instancia; complementarlo con reglas de Vercel Firewall en producción.
const attempts=new Map<string,{count:number;until:number}>();
export async function GET(){return NextResponse.json({configured:adminConfigured()&&sheetsConfigured(),authenticated:isAdmin()},{headers:{'Cache-Control':'no-store'}});}
export async function POST(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'Solicitud no permitida.'},{status:403});if(!adminConfigured()||!sheetsConfigured())return NextResponse.json({error:'Falta configurar el panel y Google Sheets.'},{status:503});const now=Date.now();for(const [k,v]of attempts)if(v.until<now)attempts.delete(k);const ip=request.headers.get('x-forwarded-for')?.split(',')[0]||'unknown';const attempt=attempts.get(ip)||{count:0,until:now+900000};if(attempt.count>=5)return NextResponse.json({error:'Espera unos minutos antes de reintentar.'},{status:429});if(attempts.size>1000)attempts.delete(attempts.keys().next().value!);attempt.count++;attempts.set(ip,attempt);try{const raw=await request.text();if(raw.length>2000)throw Error();const body=JSON.parse(raw);if(typeof body.password!=='string'||!matchesPassword(body.password))throw Error();const response=NextResponse.json({ok:true});response.cookies.set(cookieName,sessionToken(),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:8*3600});return response;}catch{return NextResponse.json({error:'No se pudo iniciar sesión.'},{status:401});}}
export async function DELETE(request:Request){if(!sameOrigin(request))return NextResponse.json({error:'Solicitud no permitida.'},{status:403});const response=NextResponse.json({ok:true});response.cookies.set(cookieName,'',{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge:0});return response;}
