const {strict:assert}=require('node:assert');const fs=require('node:fs');const ts=require('typescript');
const code=ts.transpileModule(fs.readFileSync('app/api/booking/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;
function handler({configured=true,providerOk=true}={}){let calls=[];const module={exports:{}};const req=name=>name==='next/server'?{NextResponse:{json:(body,options)=>({status:options?.status||200,body})}}:name==='@/lib/site'?{officialEmail:'team@example.test'}:name==='@/data/artists'?{artists:[{name:'Forty2'},{name:'A.X TOKYO'}]}:{siteUrl:'https://caosrecords.vercel.app'};const fetch=async(url,options)=>{calls.push({url,options});return {ok:providerOk,json:async()=>({id:'mock-email'})};};new Function('exports','module','require','process','fetch',code)(module.exports,module,req,{env:configured?{RESEND_API_KEY:'fake-test-key',BOOKING_FROM_EMAIL:'sender@example.test'}:{}},fetch);return {post:module.exports.POST,calls};}
const body={id:'00000000-0000-4000-8000-000000000001',website:'',fields:{'Nombre completo':'Prueba','Correo electrónico':'visitor@example.test',Artista:'A.X TOKYO',País:'Panamá',Ciudad:'Panamá',Mensaje:'Evento de prueba'}};
function request(data=body,origin='https://caosrecords.vercel.app'){return new Request('https://caosrecords.vercel.app/api/booking',{method:'POST',headers:{origin,'content-type':'application/json','x-forwarded-for':'127.0.0.1'},body:JSON.stringify(data)});}
(async()=>{let h=handler({configured:false});assert.equal((await h.post(request())).status,503);assert.equal(h.calls.length,0);
h=handler();assert.equal((await h.post(request(body,'https://foreign.example'))).status,403);assert.equal((await h.post(request({...body,website:'spam'}))).status,400);assert.equal((await h.post(request({...body,fields:{...body.fields,'Correo electrónico':'wrong'}}))).status,400);assert.equal((await h.post(request({...body,fields:{...body.fields,Artista:'Inventado'}}))).status,400);assert.equal((await h.post(request({...body,fields:{...body.fields,Mensaje:'x'.repeat(5001)}}))).status,400);assert.equal(h.calls.length,0);
assert.equal((await h.post(request())).status,200);const sent=JSON.parse(h.calls[0].options.body);assert.deepEqual(sent.to,['team@example.test']);assert.equal(sent.reply_to,'visitor@example.test');assert.equal(h.calls[0].options.headers['Idempotency-Key'],'booking/'+body.id);
for(let i=0;i<4;i++)assert.equal((await h.post(request())).status,200);assert.equal((await h.post(request())).status,429);
h=handler({providerOk:false});const failed=await h.post(request());assert.equal(failed.status,502);assert.equal(failed.body.ok,undefined);
console.log('Correcto: validación, origen, configuración ausente, éxito simulado, errores de proveedor, idempotencia y límite. Ningún envío real.');})().catch(e=>{console.error(e);process.exit(1)});
